-- Generated by multilingual pipeline (fr): strings_yellow
return {
  ["A: done"] = "A: Terminer",
  ["HI    %d"] = "RECORD    %d",
  ["New record!"] = "Nouveau record!",
  ["SCORE %d"] = "SCORE %d",
}
