-- Generated by multilingual pipeline (fr): type_names
return {
  ["BUG"] = "INSECTE",
  ["DRAGON"] = "DRAGON",
  ["ELECTRIC"] = "ELECTRIK",
  ["FIGHTING"] = "COMBAT",
  ["FIRE"] = "FEU",
  ["FLYING"] = "VOL",
  ["GHOST"] = "SPECTRE",
  ["GRASS"] = "PLANTE",
  ["GROUND"] = "SOL",
  ["ICE"] = "GLACE",
  ["NORMAL"] = "NORMAL",
  ["POISON"] = "POISON",
  ["PSYCHIC_TYPE"] = "PSY",
  ["ROCK"] = "ROCHE",
  ["WATER"] = "EAU",
}
